### ISSUE TITLE
Org Mode markup pack :enhancement:

### ISSUE THREAD

**Issue by symera** [kettek/open-markup-editor#43]
First of all, thank you for sharing your work.

I would really like to see support for [org mode](https://github.com/daitangio/org-mode-parser). Just as a suggestion for another neat markup pack, if it is feasible without much effort.

**Comment by kettek** [comment]
I am completely unfamiliar but I am completely open to this.

From a cursory glance it looks like that org mode library can emit HTML so it should be fairly trivial to create a new markup pack to support org. I'll look into implementing this, likely over this weekend.

**Comment by kettek** [comment]
Unfortunately that library doesn't seem to be handling much of the org mode test files I've been throwing at it. I tried a couple others that were rather terrible and buggy. Additionally, the API can barely count as documented.

However, I found https://github.com/orgapp/orgajs which seems quite promising. It gives immediately good impressions and appears to be quite active. It's split into a few distinct packages, however looks to be easy enough to process as shown [here](https://github.com/orgapp/orgajs/blob/master/examples/example/index.js).

**Comment by kettek** [comment]
API is also a bit lackluster but the code looks better, at least.

**Comment by kettek** [comment]
Using the syntax.org test file from the orgajs library, I have the following rendering:

![ome-org](https://user-images.githubusercontent.com/12402742/114520348-34800f80-9bf6-11eb-882d-c30bb1f4a1b9.gif)

Unfortunately, it doesn't look like everything is supported properly yet. I'll probably make a separate repository for reorg support since the available libraries aren't quite there yet. You will still be able to install the pack through OME's built-in pack downloader (which supports github/gitlab/gitea based releases).

**Comment by symera** [comment]
That already looks pretty good as far as I'm concerned.
Thank you for doing this.

**Comment by kettek** [comment]
I decided to place Org-mode support directly in the main repository alongside the other markup packs.

I will close this issue after additional testing and the next release of OME (which should be in a few days after I tidy up some other issues).

**Comment by kettek** [comment]
Apologies for the substantial delay in a new release. 3.1.0 has been released and contains direct Org Mode support (along with many other changes). This issue is being closed as such.

**Comment by symera** [comment]
No reason to apologize. Thank you for accepting and implementing!
